services:
  w_core:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - w_core_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  w_core_data:
    driver: local